let Education =
    "How satisfied are you with the quality of online educational resources available?What is the most important factor in choosing an online course or degree program ?How often do you use educational technology tools in your teaching or learning ?What is the biggest benefit of using technology in the classroom ?What are the biggest challenges you face in using technology to support student learning ?How do you think artificial intelligence will impact the education sector in the next 5 years ?What is your level of experience in the education sector ?What type of educational institution do you work in or attend ?How important is personalized learning in your educational philosophy ?What role do you think gamification will play in education in the next 2 - 3 years  ";

let Technology =
    "How do you think 5G networks will impact the technology industry in the next 2-3 years?What is the most important emerging technology trend in your opinion?How often do you adopt new technologies in your personal or professional life?What is the biggest barrier to adopting new technologies in your organization?What are the biggest challenges you face in implementing cybersecurity measures?How do you think blockchain technology will impact the technology industry in the next 5 years?What is your level of experience in the technology sector?What type of technology organization do you work in or interact with?How important is digital transformation in your organization's strategy?What role do you think artificial intelligence will play in technology innovation in the next 2-3 years";

let Health =
    "How satisfied are you with the quality of healthcare services you receive?What is the most important factor in choosing a healthcare provider?How often do you use telemedicine or online health services?What is the biggest benefit of using electronic health records?What are the biggest challenges you face in using technology to support patient care?How do you think precision medicine will impact healthcare outcomes in the next 5 years?What is your level of experience in the healthcare sector?What type of healthcare organization do you work in or interact with?How important is patient engagement in your healthcare philosophy?What role do you think wearable devices will play in healthcare in the next 2-3 years";

export { Education, Technology, Health };